// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zodvzryuvcxkksjozujq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZHZ6cnl1dmN4a2tzam96dWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTY5MzQsImV4cCI6MjA2MDU5MjkzNH0.SbiCzfg1jUh8vg-9SAq_idL3Z9fAeNfZwULesNWCTvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);